import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useContext } from 'react';
import { MyContext, MyContextType } from '@/context/mycontext';
import BlogCard from '@/components/BlogCard';




export default function Home() {

  const { allBlogs,data } = useContext<MyContextType>(MyContext);

  const handleFavourites=(status:boolean)=>{
if(status){
  console.log("Remove from Favourite")
}else{
  console.log("Add to Favourite")
}
  }

  console.log(allBlogs,data )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {allBlogs.map(((blog, i) => (
          <BlogCard
          onClick={()=>handleFavourites(blog.favourites['63fc9137279e3c2d73025d80'])}
          
          favourites={blog.favourites['63fc9137279e3c2d73025d80'] ? "Remove" : "Add"}
          category={blog.category}
          image={`https://i.ibb.co/jWTQB1f/IMG-20230219-012652.jpg`}
          content={blog.content}
          date={blog.date}
          title={blog.title}
          username={blog.userName}
          key={i}
        ></BlogCard>)))}
      </div>
    </>
  )
}
