import React, { useContext, useState } from 'react'
import { Box, useToast } from '@chakra-ui/react'
import Textarea from "../components/TextArea"
import Select from "../components/Select"
import { MyContext, MyContextType, serverUrl } from '@/context/mycontext'
import Head from 'next/head'
import PleaseSignin from '@/components/PleaseSignin'
import Image from 'next/image'
import styles from '../styles/WriteBlog.module.css'


const todayDate = () => {
  const currentDate = new Date();
  const year = currentDate.getFullYear();
  const month = String(currentDate.getMonth() + 1).padStart(2, '0');
  const day = String(currentDate.getDate()).padStart(2, '0');

  return `${year}-${month}-${day}`;

}


const WriteBlog = () => {


  const toast = useToast()
  const { data } = useContext<MyContextType>(MyContext);

  const initialData = {
    title: "",
    date: todayDate(),
    content: "",
    category: "Tech",
    image: "",
    
  }
  const options = [
    { value: 'Tech' },
    { value: 'Humour' },
    { value: 'Entertainment' },
    { value: 'Sports' },
    { value: 'Economy' }
  ]

  const [blogData, setBlogData] = useState(initialData)
  const [writing,setWriting]=useState(false)

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { title, value } = event.target
    setBlogData({ ...blogData, [title]: value })
  }

  const handleContentChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setBlogData({ ...blogData, content: event.target.value })
  }

  const handleSelectChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setBlogData({ ...blogData, category: event.target.value })
  }

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setWriting(true)
    console.log(blogData)

    await fetch(`${serverUrl}/blogs`, {
      method: "POST",
      mode: "cors",
      headers: {
        "Content-Type": "application/json",
        "authorization": `${data.token}`
      },
      body: JSON.stringify(blogData),
    }).then(response => {
      if (response.ok) {
        setWriting(false)
        toast({
          title: 'Blog Posted, will be live within few seconds.',
          status: 'success',
          duration: 2500,
          isClosable: true,
        })



      }
      else {
        setWriting(false)
        toast({
          title: `Error Occured Please Try Again.`,
          status: 'error',
          isClosable: true,
        })
      }
    })
      .catch(error => {
        setWriting(false)
        toast({
          title: `Error Occured Please Try Again.`,
          status: 'error',
          isClosable: true,
        })

      });


  }




  return (
    <div>
      <Head>
        <title>Write Blog | Ice Melon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box 
     >{!data.token ? <div className={styles.Position}><PleaseSignin /></div>
         : writing ? <div className={styles.Position}><Image
       alt={'writing'}
       src={'https://i.ibb.co/W0MDPZ2/write-Cute.gif'}
       width={350}
       height={200}
   /> </div>
       : <><div className="form">
        <form method="post"
          onSubmit={handleSubmit}
          className={styles.Form}>
          <label className={styles.Label}>Title:</label>
          <input
          placeholder='Enter Blog Title'
            value={blogData.title}
            onChange={handleChange}
            type="text"
            title="title" 
            className={styles.Input}
            required/>
          <label className={styles.Label}>Select Category:</label>
          <Select
            value={blogData.category}
            onChange={handleSelectChange}
            options={options} />
          <label  className={styles.Label}>Content:</label>
          <Textarea
            placeholder='Start writing here...'
            value={blogData.content}
            onChange={handleContentChange} />
          <button 
          className={styles.Button}
          type="submit">Finalize Blog</button>
        </form>
      </div></>}</Box>

    </div>
  )
}

export default WriteBlog